// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as it will be overwritten.
//
// For more information, please visit:
// https://firebase.google.com/docs/build

import { initializeApp, getApps, getApp, FirebaseApp } from "firebase/app";

const firebaseConfig = {
  "projectId": "studio-2705179619-e376d",
  "appId": "1:533733919681:web:a57016c2cc55e6edf93d40",
  "apiKey": "AIzaSyCZII37Vm4rlEKqBUBwrQMSJL7vE8qEjMA",
  // CRITICAL FIX: Use Vercel domain to avoid third-party cookie blocking
  // See: https://firebase.google.com/docs/auth/web/redirect-best-practices
  "authDomain": process.env.NEXT_PUBLIC_VERCEL_URL || "focus-flow-seven-orpin.vercel.app",
  "measurementId": "",
  "messagingSenderId": "533733919681"
};

function getFirebaseApp(): FirebaseApp {
  if (getApps().length) {
    return getApp();
  }
  return initializeApp(firebaseConfig);
}

export { getFirebaseApp, firebaseConfig };
